BIG <- read.table("household_power_consumption.txt", sep = ";", header=T)
BIG$Date <- as.Date(BIG$Date, format="%d/%m/%Y")
power <- BIG[BIG$Date >= as.Date("2007-02-01") & BIG$Date <= as.Date("2007-02-02"),]
daylist <- weekdays(power$Date)
summary(power4=="Thursday")
power$Sub_metering_1 <- as.numeric(as.character(power$Sub_metering_1))
power$Sub_metering_2 <- as.numeric(as.character(power$Sub_metering_2))
power$Sub_metering_3 <- as.numeric(as.character(power$Sub_metering_3))
plot(power$Sub_metering_1, type="l", ylab = "Energy sub metering", xlab = "", xaxt="n")
axis(1, at = c(1,1441,2881), labels=c("Thu", "Fri", "Sat"))
points(power$Sub_metering_2, col = "red", type = "l")
points(power$Sub_metering_3, col = "blue", type = "l")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1)
dev.copy(png, file="plot3.png", width = 480, height = 480)
dev.off()